### ISSUE TITLE
matlab style short circuit operator

### ISSUE THREAD

**Issue by jsta** [aeolianine/octave-networks-toolbox#1]
"dijkstra.m" throws an error when evaluating the if statement "if length(target)>0 & u==target"
I was able to fix by changing to:
if length(target)>0 && u==target %added && instead of single &

Thanks for the great toolbox.

**Comment by aeolianine** [comment]
Hey thanks! Yes, you're right that there's a fine line between "&&" and "&":
https://www.gnu.org/software/octave/doc/interpreter/Short_002dcircuit-Boolean-Operators.html
I think that occurs in many places in this toolbox (Matlab legacy), and I will work on fixing it.

I, however, get a warning, not an error when I run "dijkstra.m". I'm testing this on version 3.6.4. You?
I assume you're setting target=[].

Again, thanks for the fix.

**Comment by jsta** [comment]
I am running Octave 3.8.1 using the command,

d = dijkstra(distance, start_nodes(ii),[]);

My Octave script is being funnelled through [RcppOctave](https://github.com/renozao/RcppOctave) so maybe this is the issue.

**Comment by aeolianine** [comment]
I've been moving to short-style operator in all functions anyway, so I've incorporated your change and changed other functions as well. Thanks for the suggestion.
